### ISSUE TITLE
Async Functions en Jasmine

### ISSUE THREAD

**Issue by ihojmanb** [kerkox/red_bicicletas#5]
Hola!

al correr el spec bicicleta_test.spec.js me tira varios errores de TimeOut. Te ocurre lo mismo?
Estoy siguiendo el mismo curso de la Universidad Austral y no he podido salir de ese problema con Jasmine.

**Comment by kerkox** [comment]
Hola, en este momento ya actualice el repositorio, y para contarte tambien que las funciones async deben de recibir el parametro done que es una funcion que se llama cuando se termina la funcion async

[Documentacion de jest donde se explica el uso de done()](https://jestjs.io/docs/es-ES/asynchronous#callbacks)
